### PR TITLE
Failure is an option

### PR DESCRIPTION
**Pull request by marksteward**
To address #657.

### CODE REVIEW

**Comment by russss** [comment]
What's the rationale for adding the `late-failed` state rather than just using `failed`? I'm a bit concerned it might be easy to miss that state (as it's not very common).

(Perhaps it might be better to have an array column of previous states if we need visibility into the exact state changes?)

**Comment by marksteward** [comment]
That's just there in case we need to treat them differently (e.g. sending for emails). I don't think it's crucial, and we can reconstruct it from payment.versions if necessary.

**Comment by russss** [comment]
I think if we want to send a different email it's probably best to pass both the previous state and the current state into the email template, rather than having a completely new state.

**Comment by marksteward** [comment]
Yeah it's just an in-case. I'll remove it.

**Pull request merged**
