### PR TITLE
Update mailing list sign up to read 2022 instead of 2020

### PR DESCRIPTION
**Pull request by anorthall**
I don't think this needs any further explanation!

### CODE REVIEW

**Review by idnorton — APPROVED** [review]
:+1:

**Review by idnorton — CHANGES_REQUESTED** [review]
We had a quick chat about this on IRC and would like to get this moved to a template date something akin to `{{event_start.year}}` if that's possible?

Thanks :)

**Comment by anorthall** [comment]
> We had a quick chat about this on IRC and would like to get this moved to a template date something akin to `{{event_start.year}}` if that's possible?
> 
> Thanks :)

Done!

**Review by idnorton — APPROVED** [review]
Looks good, thanks :)

**Pull request merged**
